LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

AKMD_DEVICE_TYPE=9911
# Define Device
ifeq ($(AKMD_DEVICE_TYPE), 8975)
DEVICE_STRING=8975
else ifeq ($(AKMD_DEVICE_TYPE), 8963)
DEVICE_STRING=8963
else ifeq ($(AKMD_DEVICE_TYPE), 9912)
DEVICE_STRING=09912
else ifeq ($(AKMD_DEVICE_TYPE), 9911)
DEVICE_STRING=09911
else
$(error AKMD_DEVICE_TYPE is not defined)
endif

LOCAL_PREBUILT_LIBS := libSmartCompass/libAK09911wPGplus.a
LOCAL_MODULE_TAGS := optional
include $(BUILD_MULTI_PREBUILT)

include $(CLEAR_VARS)

# Define Device
ifeq ($(AKMD_DEVICE_TYPE), 8975)
DEVICE_STRING=8975
LOCAL_CFLAGS := -DAKMD_AK8975
else ifeq ($(AKMD_DEVICE_TYPE), 8963)
DEVICE_STRING=8963
LOCAL_CFLAGS := -DAKMD_AK8963
else ifeq ($(AKMD_DEVICE_TYPE), 9912)
DEVICE_STRING=09912
LOCAL_CFLAGS := -DAKMD_AK09912
else ifeq ($(AKMD_DEVICE_TYPE), 9911)
DEVICE_STRING=09911
LOCAL_CFLAGS := -DAKMD_AK09911
else
$(error AKMD_DEVICE_TYPE is not defined)
endif


LOCAL_C_INCLUDES += \
	$(LOCAL_PATH) \
	$(LOCAL_PATH)/libSmartCompass \
	hardware/qcom/sensors/

LOCAL_SRC_FILES += \
	AKMD_APIs.c \
	FileIO.c \
	Measure.c \
	akm_wrapper.c

LOCAL_CFLAGS += -DAKSC_DISABLE_D6D

## Enable ALOGE
#LOCAL_CFLAGS += -UNDEBUG
#LOCAL_CFLAGS += -DENABLE_AKMDEBUG=1
#LOCAL_CFLAGS += -DAKM_LOG_ENABLE
#LOCAL_CFLAGS += -DENABLE_AKM_PG
#LOCAL_CFLAGS += -DAKMD_DISABLE_DOEPLUS

LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)
LOCAL_WHOLE_STATIC_LIBRARIES += libAK09911wPGplus
LOCAL_SHARED_LIBRARIES += liblog
LOCAL_MODULE:=libcalmodule_akm
LOCAL_MODULE_TAGS := optional
LOCAL_PRELINK_MODULE := false
include $(BUILD_SHARED_LIBRARY)

